import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {dirname,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {chromium} from 'playwright';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const output=resolve(root,'evidence/browser');
await mkdir(output,{recursive:true});
const html=await readFile(resolve(root,'play.html'));
const sha=createHash('sha256').update(html).digest('hex');
const checks=[];
console.log(JSON.stringify({pid:process.pid,sourceSha256:sha,action:'offline functional browser checks'}));
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});
const url=pathToFileURL(resolve(root,'play.html')).href;
const report={sourceSha256:sha,browser:browser.version(),checks,passed:false};
let context,page;
const errors=[],requests=[],dialogs=[];
async function check(profile,name,fn){const row={profile,name,passed:false};checks.push(row);try{await fn();row.passed=true;console.log(JSON.stringify({profile,name,passed:true}));}catch(error){row.error=String(error);throw error;}}
async function fresh(width=1920,height=1080,clock=false){if(context)await context.close();context=await browser.newContext({viewport:{width,height},offline:true});page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push(r.url()));page.on('dialog',d=>{dialogs.push(d.message());void d.dismiss();});if(clock)await page.clock.install();await page.goto(url);await page.waitForTimeout(220);}
async function begin(count=2,bots=false){await page.locator('#rounds').selectOption('1');await page.locator('#seconds').selectOption('60');for(let n=2;n<count;n++)await page.locator('#add-player').click();if(bots)for(let n=2;n<=count;n++)await page.getByLabel(`Player ${n} type`,{exact:true}).selectOption(['easy','normal','sharp'][(n-2)%3]);await page.getByRole('button',{name:'Let’s play'}).click();}
async function ready(){await page.locator('#ready').click();}
async function lock(){await page.getByRole('button',{name:'Lock my',exact:false}).click();}
async function finishVotes(humans=2){let previousCategory=0;for(let step=0;step<12;step++){if(await page.locator('.score-row').count()>0)return;let category=0;for(let voter=0;voter<humans;voter++){await ready();const text=await page.locator('.session-top .eyebrow').innerText();const current=Number(text.match(/category (\d+) of 12/i)?.[1]);assert(current>previousCategory&&current<=12);if(voter===0)category=current;else assert.equal(current,category);assert(await page.locator('.vote-card').count()>0,'empty categories need no ballots');await lock();}previousCategory=category;}assert(await page.locator('.score-row').count()>0);}

try {
  await check('source','HTML embeds its scripts/styles and blocks network by CSP',async()=>{const text=html.toString();assert(!/<(?:script|link)[^>]+(?:src|href)\s*=/i.test(text));assert(text.includes("connect-src 'none'"));assert(text.includes('prefers-reduced-motion:reduce'));const license=await readFile(resolve(root,'node_modules/zod/LICENSE'),'utf8');assert(text.includes(license.replace(/--/g,'- -').trim()),'full bundled Zod copyright and permission notice preserved');const original=await readFile(resolve(root,'LICENSE'),'utf8');assert(text.includes(original.replace(/--/g,'- -').trim()),'full original MIT copyright and permission notice preserved');assert(text.includes('<!-- Original Category Rush'));assert(!text.includes('<!- -'));assert(!text.includes('- ->'));});
  for(const [profile,width,height] of [['desktop',1920,1080],['phone',390,844]]){
    await fresh(width,height);
    await check(profile,'setup and active screen have no horizontal overflow',async()=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:resolve(output,`${profile}-setup.png`),fullPage:true});});
    await check(profile,'named players are safely escaped; 12 labeled keyboard inputs',async()=>{await page.getByLabel('Player 1 name',{exact:true}).fill('<img src=x>');await begin();assert.equal(await page.locator('.handover img').count(),0);assert.match(await page.locator('.handover h2').innerText(),/<img src=x>/);await ready();assert.equal(await page.locator('.answer-input').count(),12);for(let i=0;i<12;i++){const field=page.locator(`#answer-${i}`);assert(await field.getAttribute('aria-describedby'));}assert.equal(await page.evaluate(()=>document.activeElement?.id),'answer-0');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement?.id),'answer-1');assert.equal(await page.locator('.answer-input').count(),12);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});
    let letter,probe;
    await check(profile,'private handover removes previous answers from the DOM',async()=>{letter=(await page.locator('.letter-badge').innerText()).trim();probe=`${letter} private-probe`;for(let i=0;i<12;i++)await page.locator(`#answer-${i}`).fill(i===0?probe:`${letter} first-${i}`);await lock();assert(!await page.locator('#main').innerText().then(t=>t.includes(probe)));assert.equal(await page.locator('.answer-input').count(),0);await ready();assert.equal(await page.locator('#answer-0').inputValue(),'');});
    await check(profile,'host pause freezes time and preserves draft; keyboard modal traps focus',async()=>{await page.locator('#answer-0').fill(probe);const before=await page.locator('#timer').innerText();await page.waitForTimeout(1100);const timer=await page.locator('#timer').innerText();assert.notEqual(timer,before,'native countdown advances with wall time');await page.locator('#vip-button').click();await page.waitForTimeout(1100);assert.equal(await page.locator('#timer').innerText(),timer);await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement?.id),'host-end');await page.keyboard.press('Tab');assert.equal(await page.getByRole('button',{name:'Resume game'}).evaluate(e=>document.activeElement===e),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#answer-0').inputValue(),probe);});
    await check(profile,'author names are absent from anonymous voting cards; duplicates marked zero',async()=>{for(let i=1;i<12;i++)await page.locator(`#answer-${i}`).fill(`${letter} second-${i}`);await lock();await ready();assert.equal(await page.locator('.vote-card').count(),1);const text=await page.locator('.vote-card').innerText();assert(text.includes(probe));assert(text.includes('Shared answer (2)'));assert(!text.includes('Sam'));assert(!text.includes('<img src=x>'));await page.screenshot({path:resolve(output,`${profile}-review.png`),fullPage:true});await lock();await ready();await lock();});
    await check(profile,'all 12 review categories advance; duplicate and rejected-answer scoring come from the actual core',async()=>{for(let category=1;category<12;category++)for(let voter=0;voter<2;voter++){await ready();assert.match(await page.locator('.session-top .eyebrow').innerText(),new RegExp(`category ${category+1} of 12`,'i'));if(category===1){const rejected=page.locator('.vote-card').filter({hasText:`${letter} first-1`}).locator('[data-value="false"]');await rejected.click();assert.equal(await rejected.getAttribute('aria-pressed'),'true');await page.locator('.vote-card').filter({hasText:`${letter} second-1`}).locator('[data-value="true"]').click();}await lock();}assert.equal(await page.locator('.score-row').count(),2);assert.deepEqual(await page.locator('.score-row .points').allTextContents(),['11','10']);assert.match(await page.locator('.receipt-category').first().innerText(),/Duplicate · 0/);assert.match(await page.locator('.receipt-category').first().innerText(),/Sam/);assert.equal(await page.locator('.receipt-category img').count(),0);await page.locator('.receipt-category').nth(1).locator('summary').click();assert.match(await page.locator('.receipt-category').nth(1).innerText(),/Voted out · 0/);await page.screenshot({path:resolve(output,`${profile}-scores.png`),fullPage:true});});
    await check(profile,'final results rank the winner and allow a fresh seeded game',async()=>{await page.locator('#next-round').click();assert.match(await page.locator('.session-top h2').innerText(),/Sam wins!/);assert.equal(await page.locator('#next-round').innerText().then(t=>t.startsWith('Play again')),true);await page.screenshot({path:resolve(output,`${profile}-final.png`),fullPage:true});await page.locator('#next-round').click();assert.equal(await page.locator('#setup-form').count(),1);assert.equal(await page.locator('#seed').inputValue(),'43');});
    await check(profile,'reduced motion disables entrance animation',async()=>{await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.page-enter').evaluate(e=>getComputedStyle(e).animationName),'none');});
    await fresh(width,height,true);
    await check(profile,'timer expiry locks typed answers and waits at a private handover',async()=>{await begin();await ready();const letter=(await page.locator('.letter-badge').innerText()).trim();await page.locator('#answer-0').fill(`${letter} timeout-probe`);await page.clock.fastForward(61000);assert.equal(await page.locator('.handover').count(),1);assert.match(await page.locator('.handover h2').innerText(),/Sam/);await page.clock.fastForward(180000);assert.equal(await page.locator('.handover').count(),1);await ready();assert.equal(await page.locator('#timer').innerText(),'1:00');await page.locator('#vip-button').click();await page.locator('#host-end').click();await page.locator('#confirm-end').click();assert.match(await page.locator('.session-top .eyebrow').innerText(),/final results/i);assert.deepEqual(await page.locator('.score-row .points').allTextContents(),['0','0']);assert.match(await page.locator('.session-top h2').innerText(),/tie!/);});
  }
  for(let count=2;count<=8;count++){
    await fresh();
    await check('desktop',`${count} seats with easy/medium/strong bots play a whole game`,async()=>{await begin(count,true);await ready();await lock();await finishVotes(1);assert.equal(await page.locator('.score-row').count(),count);await page.locator('#next-round').click();assert.match(await page.locator('.session-top .eyebrow').innerText(),/final results/i);assert.equal(await page.locator('.score-row').count(),count);});
  }
  await check('runtime','offline file made zero network calls and raised no errors or dialogs',async()=>{assert.equal(errors.length,0,JSON.stringify(errors));assert.equal(dialogs.length,0);assert(requests.length>0);assert(requests.every(request=>request.startsWith('file:')));});
  await check('provenance','HTML stayed byte-identical during the whole browser suite',async()=>{assert.equal(createHash('sha256').update(await readFile(resolve(root,'play.html'))).digest('hex'),sha);});
  report.passed=checks.every(c=>c.passed);
} catch(error){report.failure=String(error);process.exitCode=1;}
finally{if(context)await context.close();await browser.close();report.runtime={errors,dialogs,networkRequests:requests.filter(request=>!request.startsWith('file:'))};await writeFile(resolve(output,'functional-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({sourceSha256:sha,passed:report.passed,checks:checks.length,failure:report.failure}));}
