import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const baseline = process.argv.includes('--baseline');
const { AUTHORED } = await import(baseline ? '../evidence/breadth-baseline-authored.mjs' : '../content/authored.mjs');
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const LETTERS = [...'ABCDEFGHIJKLMNOPRSTW'];
let theme = '', position = 0;
const categories = [];
for (const raw of AUTHORED.trim().split('\n')) {
  const line = raw.trim();
  if (!line) continue;
  if (line.startsWith('@')) { theme = line.slice(1); position = 0; continue; }
  const [prompt, examples, ...rest] = line.split('|');
  if (!theme || rest.length || !prompt || !examples) throw new Error(`Malformed authored row: ${line}`);
  const answers = {};
  for (const value of examples.split(';')) {
    const answer = value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').trim();
    const letter = answer.replace(/^(?:a|an|the)\s+/, '')[0]?.toUpperCase();
    if (!LETTERS.includes(letter)) continue;
    (answers[letter] ??= []).push(answer);
  }
  const ordered = Object.fromEntries(LETTERS.filter(letter => answers[letter]).map(letter => [letter, [...new Set(answers[letter])]]));
  categories.push({ id: `${theme}-${String(++position).padStart(2, '0')}`, prompt, clarification: 'Give a real example. Established compound names count; decorative modifiers do not.', theme, answers: ordered });
}
const pack = { schemaVersion: 1, lang: 'en', letters: LETTERS, categories };
const json = JSON.stringify(pack, null, 2) + '\n';
const ts = `// GENERATED by scripts/generate-content.mjs. Edit content/authored.mjs.\nexport interface Category { readonly id: string; readonly prompt: string; readonly clarification: string; readonly theme: string; readonly answers: Readonly<Record<string, readonly string[]>>; }\nexport const LETTERS: readonly string[] = ${JSON.stringify(LETTERS)};\nexport const CATEGORIES: readonly Category[] = ${JSON.stringify(categories, null, 2)};\n`;
const outputs = baseline ? [['evidence/breadth-baseline-content.json', json]] : [['content/categories.json', json], ['content/categories.ts', ts]];
for (const [name, data] of outputs) {
  const target = resolve(ROOT, name);
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== data) throw new Error(`${name} needs regeneration`);
  } else writeFileSync(target, data);
}
console.log(`${categories.length} original categories; ${LETTERS.length} letters; ${categories.reduce((n, c) => n + Object.values(c.answers).flat().length, 0)} curated examples`);
