// Generated by scripts/chunk-international.py; original licensed bytes.
import chunk0 from '../data/international/six/db6-0303.000.chunk';
import index0303 from '../data/international/six/db6-0303.idx';
import chunk1 from '../data/international/six/db6-0312.000.chunk';
import index0312 from '../data/international/six/db6-0312.idx';
import chunk2 from '../data/international/six/db6-0321.000.chunk';
import chunk3 from '../data/international/six/db6-0321.001.chunk';
import index0321 from '../data/international/six/db6-0321.idx';
import chunk4 from '../data/international/six/db6-0330.000.chunk';
import index0330 from '../data/international/six/db6-0330.idx';
import chunk5 from '../data/international/six/db6-0402.000.chunk';
import index0402 from '../data/international/six/db6-0402.idx';
import chunk6 from '../data/international/six/db6-0411.000.chunk';
import index0411 from '../data/international/six/db6-0411.idx';
import chunk7 from '../data/international/six/db6-0420.000.chunk';
import index0420 from '../data/international/six/db6-0420.idx';
import chunk8 from '../data/international/six/db6-0501.000.chunk';
import index0501 from '../data/international/six/db6-0501.idx';
import chunk9 from '../data/international/six/db6-0510.000.chunk';
import index0510 from '../data/international/six/db6-0510.idx';
import chunk10 from '../data/international/six/db6-1212.000.chunk';
import chunk11 from '../data/international/six/db6-1212.001.chunk';
import index1212 from '../data/international/six/db6-1212.idx';
import chunk12 from '../data/international/six/db6-1221.000.chunk';
import chunk13 from '../data/international/six/db6-1221.001.chunk';
import chunk14 from '../data/international/six/db6-1221.002.chunk';
import chunk15 from '../data/international/six/db6-1221.003.chunk';
import index1221 from '../data/international/six/db6-1221.idx';
import chunk16 from '../data/international/six/db6-1230.000.chunk';
import chunk17 from '../data/international/six/db6-1230.001.chunk';
import index1230 from '../data/international/six/db6-1230.idx';
import chunk18 from '../data/international/six/db6-1302.000.chunk';
import chunk19 from '../data/international/six/db6-1302.001.chunk';
import index1302 from '../data/international/six/db6-1302.idx';
import chunk20 from '../data/international/six/db6-1311.000.chunk';
import chunk21 from '../data/international/six/db6-1311.001.chunk';
import chunk22 from '../data/international/six/db6-1311.002.chunk';
import chunk23 from '../data/international/six/db6-1311.003.chunk';
import index1311 from '../data/international/six/db6-1311.idx';
import chunk24 from '../data/international/six/db6-1320.000.chunk';
import index1320 from '../data/international/six/db6-1320.idx';
import chunk25 from '../data/international/six/db6-1401.000.chunk';
import index1401 from '../data/international/six/db6-1401.idx';
import chunk26 from '../data/international/six/db6-1410.000.chunk';
import index1410 from '../data/international/six/db6-1410.idx';
import chunk27 from '../data/international/six/db6-2121.000.chunk';
import chunk28 from '../data/international/six/db6-2121.001.chunk';
import index2121 from '../data/international/six/db6-2121.idx';
import chunk29 from '../data/international/six/db6-2130.000.chunk';
import chunk30 from '../data/international/six/db6-2130.001.chunk';
import index2130 from '../data/international/six/db6-2130.idx';
import chunk31 from '../data/international/six/db6-2202.000.chunk';
import chunk32 from '../data/international/six/db6-2202.001.chunk';
import index2202 from '../data/international/six/db6-2202.idx';
import chunk33 from '../data/international/six/db6-2211.000.chunk';
import chunk34 from '../data/international/six/db6-2211.001.chunk';
import chunk35 from '../data/international/six/db6-2211.002.chunk';
import chunk36 from '../data/international/six/db6-2211.003.chunk';
import chunk37 from '../data/international/six/db6-2211.004.chunk';
import chunk38 from '../data/international/six/db6-2211.005.chunk';
import chunk39 from '../data/international/six/db6-2211.006.chunk';
import index2211 from '../data/international/six/db6-2211.idx';
import chunk40 from '../data/international/six/db6-2220.000.chunk';
import index2220 from '../data/international/six/db6-2220.idx';
import chunk41 from '../data/international/six/db6-2301.000.chunk';
import index2301 from '../data/international/six/db6-2301.idx';
import chunk42 from '../data/international/six/db6-2310.000.chunk';
import index2310 from '../data/international/six/db6-2310.idx';
import chunk43 from '../data/international/six/db6-3030.000.chunk';
import index3030 from '../data/international/six/db6-3030.idx';
import chunk44 from '../data/international/six/db6-3102.000.chunk';
import index3102 from '../data/international/six/db6-3102.idx';
import chunk45 from '../data/international/six/db6-3111.000.chunk';
import chunk46 from '../data/international/six/db6-3111.001.chunk';
import chunk47 from '../data/international/six/db6-3111.002.chunk';
import chunk48 from '../data/international/six/db6-3111.003.chunk';
import chunk49 from '../data/international/six/db6-3111.004.chunk';
import chunk50 from '../data/international/six/db6-3111.005.chunk';
import index3111 from '../data/international/six/db6-3111.idx';
import chunk51 from '../data/international/six/db6-3120.000.chunk';
import index3120 from '../data/international/six/db6-3120.idx';
import chunk52 from '../data/international/six/db6-3201.000.chunk';
import index3201 from '../data/international/six/db6-3201.idx';
import chunk53 from '../data/international/six/db6-3210.000.chunk';
import index3210 from '../data/international/six/db6-3210.idx';
import chunk54 from '../data/international/six/db6-4002.000.chunk';
import index4002 from '../data/international/six/db6-4002.idx';
import chunk55 from '../data/international/six/db6-4011.000.chunk';
import index4011 from '../data/international/six/db6-4011.idx';
import chunk56 from '../data/international/six/db6-4020.000.chunk';
import index4020 from '../data/international/six/db6-4020.idx';
import chunk57 from '../data/international/six/db6-4101.000.chunk';
import index4101 from '../data/international/six/db6-4101.idx';
import chunk58 from '../data/international/six/db6-4110.000.chunk';
import index4110 from '../data/international/six/db6-4110.idx';
import chunk59 from '../data/international/six/db6-5001.000.chunk';
import index5001 from '../data/international/six/db6-5001.idx';
import chunk60 from '../data/international/six/db6-5010.000.chunk';
import index5010 from '../data/international/six/db6-5010.idx';
export const internationalSixFiles=Object.freeze([
  Object.freeze({name:"db6-0303",byteLength:1413194,chunks:Object.freeze([chunk0]),indexText:index0303}),
  Object.freeze({name:"db6-0312",byteLength:16957986,chunks:Object.freeze([chunk1]),indexText:index0312}),
  Object.freeze({name:"db6-0321",byteLength:36118046,chunks:Object.freeze([chunk2,chunk3]),indexText:index0321}),
  Object.freeze({name:"db6-0330",byteLength:10587316,chunks:Object.freeze([chunk4]),indexText:index0330}),
  Object.freeze({name:"db6-0402",byteLength:14580828,chunks:Object.freeze([chunk5]),indexText:index0402}),
  Object.freeze({name:"db6-0411",byteLength:24366067,chunks:Object.freeze([chunk6]),indexText:index0411}),
  Object.freeze({name:"db6-0420",byteLength:2447725,chunks:Object.freeze([chunk7]),indexText:index0420}),
  Object.freeze({name:"db6-0501",byteLength:93028,chunks:Object.freeze([chunk8]),indexText:index0501}),
  Object.freeze({name:"db6-0510",byteLength:9425,chunks:Object.freeze([chunk9]),indexText:index0510}),
  Object.freeze({name:"db6-1212",byteLength:30292335,chunks:Object.freeze([chunk10,chunk11]),indexText:index1212}),
  Object.freeze({name:"db6-1221",byteLength:94198754,chunks:Object.freeze([chunk12,chunk13,chunk14,chunk15]),indexText:index1221}),
  Object.freeze({name:"db6-1230",byteLength:35902310,chunks:Object.freeze([chunk16,chunk17]),indexText:index1230}),
  Object.freeze({name:"db6-1302",byteLength:39523567,chunks:Object.freeze([chunk18,chunk19]),indexText:index1302}),
  Object.freeze({name:"db6-1311",byteLength:99400526,chunks:Object.freeze([chunk20,chunk21,chunk22,chunk23]),indexText:index1311}),
  Object.freeze({name:"db6-1320",byteLength:9592131,chunks:Object.freeze([chunk24]),indexText:index1320}),
  Object.freeze({name:"db6-1401",byteLength:719357,chunks:Object.freeze([chunk25]),indexText:index1401}),
  Object.freeze({name:"db6-1410",byteLength:55373,chunks:Object.freeze([chunk26]),indexText:index1410}),
  Object.freeze({name:"db6-2121",byteLength:42115285,chunks:Object.freeze([chunk27,chunk28]),indexText:index2121}),
  Object.freeze({name:"db6-2130",byteLength:37257641,chunks:Object.freeze([chunk29,chunk30]),indexText:index2130}),
  Object.freeze({name:"db6-2202",byteLength:40167724,chunks:Object.freeze([chunk31,chunk32]),indexText:index2202}),
  Object.freeze({name:"db6-2211",byteLength:176123092,chunks:Object.freeze([chunk33,chunk34,chunk35,chunk36,chunk37,chunk38,chunk39]),indexText:index2211}),
  Object.freeze({name:"db6-2220",byteLength:15988152,chunks:Object.freeze([chunk40]),indexText:index2220}),
  Object.freeze({name:"db6-2301",byteLength:2513926,chunks:Object.freeze([chunk41]),indexText:index2301}),
  Object.freeze({name:"db6-2310",byteLength:151616,chunks:Object.freeze([chunk42]),indexText:index2310}),
  Object.freeze({name:"db6-3030",byteLength:8683886,chunks:Object.freeze([chunk43]),indexText:index3030}),
  Object.freeze({name:"db6-3102",byteLength:20297910,chunks:Object.freeze([chunk44]),indexText:index3102}),
  Object.freeze({name:"db6-3111",byteLength:135538154,chunks:Object.freeze([chunk45,chunk46,chunk47,chunk48,chunk49,chunk50]),indexText:index3111}),
  Object.freeze({name:"db6-3120",byteLength:17834410,chunks:Object.freeze([chunk51]),indexText:index3120}),
  Object.freeze({name:"db6-3201",byteLength:4959949,chunks:Object.freeze([chunk52]),indexText:index3201}),
  Object.freeze({name:"db6-3210",byteLength:292044,chunks:Object.freeze([chunk53]),indexText:index3210}),
  Object.freeze({name:"db6-4002",byteLength:10259190,chunks:Object.freeze([chunk54]),indexText:index4002}),
  Object.freeze({name:"db6-4011",byteLength:23950475,chunks:Object.freeze([chunk55]),indexText:index4011}),
  Object.freeze({name:"db6-4020",byteLength:9915745,chunks:Object.freeze([chunk56]),indexText:index4020}),
  Object.freeze({name:"db6-4101",byteLength:5322403,chunks:Object.freeze([chunk57]),indexText:index4101}),
  Object.freeze({name:"db6-4110",byteLength:282317,chunks:Object.freeze([chunk58]),indexText:index4110}),
  Object.freeze({name:"db6-5001",byteLength:3249008,chunks:Object.freeze([chunk59]),indexText:index5001}),
  Object.freeze({name:"db6-5010",byteLength:232867,chunks:Object.freeze([chunk60]),indexText:index5010}),
]);
