// Generated by scripts/chunk-international.py; metadata only, no data copies.
import index0303 from '../data/international/six/db6-0303.idx';
import index0312 from '../data/international/six/db6-0312.idx';
import index0321 from '../data/international/six/db6-0321.idx';
import index0330 from '../data/international/six/db6-0330.idx';
import index0402 from '../data/international/six/db6-0402.idx';
import index0411 from '../data/international/six/db6-0411.idx';
import index0420 from '../data/international/six/db6-0420.idx';
import index0501 from '../data/international/six/db6-0501.idx';
import index0510 from '../data/international/six/db6-0510.idx';
import index1212 from '../data/international/six/db6-1212.idx';
import index1221 from '../data/international/six/db6-1221.idx';
import index1230 from '../data/international/six/db6-1230.idx';
import index1302 from '../data/international/six/db6-1302.idx';
import index1311 from '../data/international/six/db6-1311.idx';
import index1320 from '../data/international/six/db6-1320.idx';
import index1401 from '../data/international/six/db6-1401.idx';
import index1410 from '../data/international/six/db6-1410.idx';
import index2121 from '../data/international/six/db6-2121.idx';
import index2130 from '../data/international/six/db6-2130.idx';
import index2202 from '../data/international/six/db6-2202.idx';
import index2211 from '../data/international/six/db6-2211.idx';
import index2220 from '../data/international/six/db6-2220.idx';
import index2301 from '../data/international/six/db6-2301.idx';
import index2310 from '../data/international/six/db6-2310.idx';
import index3030 from '../data/international/six/db6-3030.idx';
import index3102 from '../data/international/six/db6-3102.idx';
import index3111 from '../data/international/six/db6-3111.idx';
import index3120 from '../data/international/six/db6-3120.idx';
import index3201 from '../data/international/six/db6-3201.idx';
import index3210 from '../data/international/six/db6-3210.idx';
import index4002 from '../data/international/six/db6-4002.idx';
import index4011 from '../data/international/six/db6-4011.idx';
import index4020 from '../data/international/six/db6-4020.idx';
import index4101 from '../data/international/six/db6-4101.idx';
import index4110 from '../data/international/six/db6-4110.idx';
import index5001 from '../data/international/six/db6-5001.idx';
import index5010 from '../data/international/six/db6-5010.idx';
export const internationalSixIndexes=Object.freeze([
  Object.freeze({name:"db6-0303",byteLength:1413194,indexText:index0303}),
  Object.freeze({name:"db6-0312",byteLength:16957986,indexText:index0312}),
  Object.freeze({name:"db6-0321",byteLength:36118046,indexText:index0321}),
  Object.freeze({name:"db6-0330",byteLength:10587316,indexText:index0330}),
  Object.freeze({name:"db6-0402",byteLength:14580828,indexText:index0402}),
  Object.freeze({name:"db6-0411",byteLength:24366067,indexText:index0411}),
  Object.freeze({name:"db6-0420",byteLength:2447725,indexText:index0420}),
  Object.freeze({name:"db6-0501",byteLength:93028,indexText:index0501}),
  Object.freeze({name:"db6-0510",byteLength:9425,indexText:index0510}),
  Object.freeze({name:"db6-1212",byteLength:30292335,indexText:index1212}),
  Object.freeze({name:"db6-1221",byteLength:94198754,indexText:index1221}),
  Object.freeze({name:"db6-1230",byteLength:35902310,indexText:index1230}),
  Object.freeze({name:"db6-1302",byteLength:39523567,indexText:index1302}),
  Object.freeze({name:"db6-1311",byteLength:99400526,indexText:index1311}),
  Object.freeze({name:"db6-1320",byteLength:9592131,indexText:index1320}),
  Object.freeze({name:"db6-1401",byteLength:719357,indexText:index1401}),
  Object.freeze({name:"db6-1410",byteLength:55373,indexText:index1410}),
  Object.freeze({name:"db6-2121",byteLength:42115285,indexText:index2121}),
  Object.freeze({name:"db6-2130",byteLength:37257641,indexText:index2130}),
  Object.freeze({name:"db6-2202",byteLength:40167724,indexText:index2202}),
  Object.freeze({name:"db6-2211",byteLength:176123092,indexText:index2211}),
  Object.freeze({name:"db6-2220",byteLength:15988152,indexText:index2220}),
  Object.freeze({name:"db6-2301",byteLength:2513926,indexText:index2301}),
  Object.freeze({name:"db6-2310",byteLength:151616,indexText:index2310}),
  Object.freeze({name:"db6-3030",byteLength:8683886,indexText:index3030}),
  Object.freeze({name:"db6-3102",byteLength:20297910,indexText:index3102}),
  Object.freeze({name:"db6-3111",byteLength:135538154,indexText:index3111}),
  Object.freeze({name:"db6-3120",byteLength:17834410,indexText:index3120}),
  Object.freeze({name:"db6-3201",byteLength:4959949,indexText:index3201}),
  Object.freeze({name:"db6-3210",byteLength:292044,indexText:index3210}),
  Object.freeze({name:"db6-4002",byteLength:10259190,indexText:index4002}),
  Object.freeze({name:"db6-4011",byteLength:23950475,indexText:index4011}),
  Object.freeze({name:"db6-4020",byteLength:9915745,indexText:index4020}),
  Object.freeze({name:"db6-4101",byteLength:5322403,indexText:index4101}),
  Object.freeze({name:"db6-4110",byteLength:282317,indexText:index4110}),
  Object.freeze({name:"db6-5001",byteLength:3249008,indexText:index5001}),
  Object.freeze({name:"db6-5010",byteLength:232867,indexText:index5010}),
]);
