import { writeFileSync, mkdirSync } from 'node:fs';
import { createRng } from '../.build/contract/rng.js';
import { makeTemplate, templateLevel, greedyValue, wilson } from '../.build/jobs/G03-pack-the-hold/src/generator.js';
import { legalPlacements, placementCells } from '../.build/jobs/G03-pack-the-hold/src/geometry.js';
import { solveExact } from '../.build/jobs/G03-pack-the-hold/src/solver.js';

const policy = 'Uniform level from 12 templates; descending value; uniform legal placement; no backtracking';
function compile(level) {
  const index = new Map(level.cells.map((c, i) => [c.join(','), i]));
  return [...level.crates].sort((a, b) => b.value - a.value).map(crate => ({
    value: crate.value,
    masks: legalPlacements(level, crate).map(p => placementCells(crate, p).reduce((mask, c) => mask | (1n << BigInt(index.get(c.join(',')))), 0n)),
  }));
}
function probe(compiled, seed) {
  const rng = createRng(seed); let used = 0n; let value = 0;
  for (const crate of compiled) {
    const choices = crate.masks.filter(mask => !(mask & used));
    if (choices.length) { used |= rng.pick(choices); value += crate.value; }
  }
  return value;
}
function measure(level, trials, base) {
  const compiled = compile(level); let solved = 0;
  for (let seed = 0; seed < trials; seed++) if (probe(compiled, base + seed) === 200) solved++;
  for (let seed = 0; seed < 4; seed++) {
    if (probe(compiled, base + seed) !== greedyValue(level, base + seed)) throw new Error('calibration optimization disagrees with policy');
  }
  return solved;
}
const candidates = Array.from({ length: 120 }, (_, i) => {
  const template = makeTemplate(0x103000 + i); const level = templateLevel(template);
  if (solveExact(level).value !== 200) throw new Error('candidate not proven solvable');
  return { template, normal: measure(level, 384, 0x500000), mirrored: measure({ ...level, allowFlip: true }, 384, 0x500000) };
});
function poolTiers(allowFlip) {
  const sorted = [...candidates].sort((a, b) => (allowFlip ? b.mirrored - a.mirrored : b.normal - a.normal));
  return Array.from({ length: 10 }, (_, i) => {
    const templates = sorted.slice(i * 12, (i + 1) * 12).map(c => c.template);
    const levels = templates.map(t => templateLevel(t, 1, allowFlip)); const compiled = levels.map(compile);
    let solved = 0;
    for (let trial = 0; trial < 2000; trial++) {
      const seed = 0x600000 + trial; const variant = createRng(seed).int(0, 11); const packingSeed = seed ^ 0x5eed;
      const value = probe(compiled[variant], packingSeed);
      if (trial < 4 && value !== greedyValue(levels[variant], packingSeed)) throw Error('pool policy mismatch');
      if (value === 200) solved++;
    }
    return { difficulty: 0, templates, trials: 2000, solved, solveRate: solved / 2000, confidence95: wilson(solved, 2000), policy };
  }).sort((a, b) => b.solveRate - a.solveRate).map((tier, i) => ({ ...tier, difficulty: i + 1 }));
}
const tiers = poolTiers(false); const flip = poolTiers(true);
mkdirSync('data', { recursive: true });
writeFileSync('data/calibration.json', JSON.stringify({ schemaVersion: 1, humanRates: false, policy, candidateCount: 120, screeningTrials: 384, tiers, flip }, null, 2) + '\n');
writeFileSync('src/tiers.ts', "import type { Tier } from './types.js';\n// Generated by scripts/calibrate.mjs. Empirical policy rates, not human measurements.\nexport const TIERS: Tier[] = " + JSON.stringify(tiers, null, 2) + ';\nexport const FLIP_TIERS: Tier[] = ' + JSON.stringify(flip, null, 2) + ';\n');
console.log(JSON.stringify({ calibrated: tiers.map(t => ({ difficulty: t.difficulty, solved: t.solved, trials: t.trials, rate: t.solveRate })) }));
