import {build} from 'esbuild';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const result=await build({entryPoints:['ui.ts'],bundle:true,write:false,format:'iife',platform:'browser',target:'es2022',minify:true,legalComments:'none'});
const license=readFileSync('THIRD-PARTY-LICENSES.txt','utf8');assert.equal(license,readFileSync('node_modules/zod/LICENSE','utf8'),'the delivered notice must exactly match pinned Zod');
const code=(`/* Bundled Zod 4.6.5 — full MIT notice\n${license}*/\n`+result.outputFiles[0]!.text).replace(/<\/script/gi,'<\\/script');
const shell=readFileSync('shell.html','utf8');assert.equal(shell.split('/*__INLINE_GAME__*/').length,2);
const html=shell.replace('/*__INLINE_GAME__*/',()=>code);
assert(html.includes(license),'the standalone artifact must retain the full dependency notice');
assert(!/<script[^>]+src=|<link[^>]+href=|url\(\s*["']?https?:\/\//i.test(html),'single-file page must have no external resources');
if(process.argv.includes('--check'))assert.equal(readFileSync('play.html','utf8'),html,'rebuild play.html after UI changes');else writeFileSync('play.html',html);
console.log(`Offline HTML ${process.argv.includes('--check')?'verified':'built'}: ${Buffer.byteLength(html)} bytes`);
