import assert from 'node:assert/strict';
import {readFile,writeFile,stat} from 'node:fs/promises';
import {resolve} from 'node:path';
import {stageGuards,stageCommands,validateStageReceipt,sourceCommit} from '../../scripts/check-stages.mjs';
import {validateCurrentBrowserEvidence,hashFile} from '../../scripts/browser-evidence.mjs';
const base=resolve('.work/hosted-df-browser'),directory=base+'/extracted',head='df123c797b226c479b50a998011c1ea6d0157391',run='37870240814',html=resolve('.work/play-full-candidate-b4.html');
assert.equal(sourceCommit(),head);assert.equal(process.version,'v22.16.0');
const startedAt=new Date().toISOString(), historical=JSON.parse(await readFile(base+'/historical-git-guards.json','utf8'));
assert.equal(historical.status,'PASS');assert.equal(historical.acceptedHead,head);assert.equal(historical.sourceGuardCount,349);assert.equal(historical.gitTrackedOriginalBytes.length,206);assert.equal(historical.generatedRuntimePathsRequireCurrentByteMatch.length,143);
const guards=await stageGuards(),sourceSha256=await hashFile(html),htmlBytes=(await stat(html)).size;
assert.equal(sourceSha256,'b4f5267561bd95d68455ea5a83b936692b246d1a8ed936199c820e430a2da3eb');assert.equal(htmlBytes,1390846291);
const receipt=JSON.parse(await readFile(directory+'/.work/checks/stage-browser.json','utf8'));
validateStageReceipt(receipt,{stage:'browser',commit:head,guards,htmlSha256:sourceSha256,htmlBytes,commands:await stageCommands('browser'),runtime:process.version,runId:run,runAttempt:'1'});
await validateCurrentBrowserEvidence({browserDirectory:directory+'/.work/browser',mediaDirectory:directory+'/.work/media',htmlPath:html,sourceSha256});
assert.deepEqual(await stageGuards(),guards);assert.equal(sourceCommit(),head);
for(const doc of historical.sixCurrentDocumentationGitBridge)assert.equal(await hashFile(doc.path.replace('jobs/G10-checkers/','')),doc.currentGitSha256);
const strict=JSON.parse(await readFile(directory+'/.work/browser/checks.json','utf8')),capture=JSON.parse(await readFile(directory+'/.work/browser/capture.json','utf8'));
const result={status:'PASS',startedAt,closedAt:new Date().toISOString(),head,workflowRunId:run,workflowRunAttempt:'1',stageGuardCount:349,immutableGitOriginals:206,generatedRuntimeGuards:143,sixCurrentDocumentationGitBridge:historical.sixCurrentDocumentationGitBridge,htmlBytes,sourceSha256,stage:{startedAt:receipt.startedAt,closedAt:receipt.closedAt,commands:receipt.commands},browser:{strictRunId:strict.runId,captureRunId:capture.runId,functionalChecks:strict.checks.length+capture.checks.length,strictIntervals:2400,nativeTimestamps:2404,profiles:strict.profiles,captures:capture.profiles.map(row=>({name:row.name,gameplay:row.gameplay,video:row.video}))},scope:'Exact current df original hosted browser stage only. Actual all349 source guards, immutableGit/six-doc bridge, exact original commands/Node22/run/attempt/current whole physical b4, all2400 original strict native intervals/2404 timestamps/all60 strict and capture functional checks/current genuine clips and both original recordings fully decoded. Node, leagues, final complete acceptance and fourpart reception remain separate; no inferred allchecks, KEEP gain or Ready.'};
await writeFile(base+'/independent-browser-evidence.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,head,closedAt:result.closedAt,strictIntervals:2400,nativeTimestamps:2404,functionalChecks:60,profiles:strict.profiles,scope:result.scope}));
