// Original translations for the offline host. Owner client strings/assets are retained.
export const offlineStrings: Record<string, string> = {
  "Reveal words": "Revelar palabras",
  "Players": "Jugadores",
  "Words": "Palabras",
  "Grid": "Cuadrícula",
  "Dictionary": "Diccionario",
  "Rounds": "Rondas",
  "Seconds per person": "Segundos por persona",
  "Seed": "Semilla",
  "Who is playing?": "¿Quién juega?",
  "Name {n}": "Nombre {n}",
  "Player {n}": "Jugador {n}",
  "Person": "Persona",
  "Easy bot": "Bot fácil",
  "Normal bot": "Bot normal",
  "Sharp bot": "Bot fuerte",
  "Start Shake Up": "Empezar Shake Up",
  "How to play": "Cómo jugar",
  "Credits and word-list licences": "Créditos y licencias de las listas",
  "English": "Inglés",
  "Full word list": "Lista completa",
  "Common words (SCOWL 70)": "Palabras comunes (SCOWL 70)",
  " · Results": " · Resultados",
  "Host controls": "Controles de la partida",
  "Resume": "Reanudar",
  "Pause": "Pausar",
  "Finish turn": "Terminar turno",
  "Next card": "Siguiente tarjeta",
  "Continue": "Continuar",
  "Public stage": "Pantalla pública",
  "New game": "Nueva partida",
  "Pass the device": "Pasa el dispositivo",
  "Pass to {name}": "Pasa a {name}",
  "I’m ready": "Estoy listo",
  "Everyone else looks away. Your {seconds}-second clock starts when you’re ready.": "Los demás miran hacia otro lado. Tus {seconds} segundos empiezan cuando estés listo.",
  "{name} · private turn": "{name} · turno privado",
  "Round {round} of {total}": "Ronda {round} de {total}",
  "End this game and return to setup? Current scores will be lost.": "¿Terminar esta partida y volver a la configuración? Se perderán las puntuaciones actuales.",
  "Trace touching cubes. Shared words cancel. Each person gets the same private clock; pass the device between turns.": "Traza cubos que se toquen. Las palabras compartidas no puntúan. Cada persona tiene el mismo tiempo privado; pasa el dispositivo entre turnos.",
  "Drag across cubes and lift, or tap letters and press Submit. Keyboard: arrow keys move, Enter or Space adds a cube, Escape clears. Diagonals count; use each cube once. Qu is one cube and two letters. Minimum: 3 letters on 4×4, 4 on 5×5. Length 3–4 scores 1, 5 scores 2, 6 scores 3, 7 scores 5, 8+ scores 11. Words found by two or more players score zero. Unknown words may be accepted together at the reveal.": "Arrastra por los cubos y suelta, o toca letras y pulsa Enviar. Teclado: las flechas mueven el foco, Intro o Espacio añade un cubo, Escape borra. Las diagonales cuentan; usa cada cubo una sola vez. Qu ocupa un cubo y cuenta como dos letras. Mínimo: 3 letras en 4×4, 4 en 5×5. Las palabras de 3–4 letras valen 1 punto; 5, 2; 6, 3; 7, 5; 8 o más, 11. Las palabras encontradas por dos o más jugadores valen cero. Las palabras desconocidas pueden aceptarse para todos durante la revelación.",
  "During private turns, everyone else looks away. Handoff hides the previous list. Bots play the same board during the first turn. Public stage shows counts during the hunt.": "Durante los turnos privados, los demás miran hacia otro lado. Al pasar el dispositivo se oculta la lista anterior. Los bots juegan en el mismo tablero durante el primer turno. La pantalla pública muestra solo cantidades durante la búsqueda."
};
