#!/usr/bin/env python3
"""Deterministically split licensed original International six-piece files."""
import argparse
import hashlib
import json
from pathlib import Path
import zlib

CHUNK_BYTES = 3 * 8388608

def canonical_six():
    values = set()
    for bm in range(6):
        for bk in range(6-bm):
            for wm in range(6):
                wk = 6-bm-bk-wm
                black, white = bm+bk, wm+wk
                if wk >= 0 and 1 <= black <= 5 and 1 <= white <= 5 and black >= white and (black != white or bk >= wk):
                    values.add(f'{bm}{bk}{wm}{wk}')
    assert len(values) == 37
    return sorted(values)

def write(args):
    known = {row['file']: row for row in json.loads(args.source_manifest.read_text())}
    args.out.mkdir(parents=True, exist_ok=True)
    descriptors = []
    imports, entries, index_imports, index_entries = [], [], [], []
    counter = 0
    for material in canonical_six():
        name = 'db6-' + material
        source_name, index_name = name+'.cpr1', name+'.idx1'
        original, original_index = known[source_name], known[index_name]
        assert original['installerSha1Matches'] and original['originalDriverCrcMatches']
        assert original_index['installerSha1Matches'] and original_index['originalDriverCrcMatches']
        index = (args.source/index_name).read_bytes()
        assert len(index) == original_index['bytes'] and hashlib.sha256(index).hexdigest() == original_index['sha256']
        index.decode('ascii')
        (args.out/(name+'.idx')).write_bytes(index)
        digest, sha1, crc, size, chunks, variables = hashlib.sha256(), hashlib.sha1(), 0, 0, [], []
        with (args.source/source_name).open('rb') as source:
            for part in range(1000):
                data = source.read(CHUNK_BYTES)
                if not data:
                    break
                filename = f'{name}.{part:03}.chunk'
                (args.out/filename).write_bytes(data)
                digest.update(data); sha1.update(data); crc = zlib.crc32(data, crc); size += len(data)
                chunks.append({'file':filename,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
                variable = 'chunk' + str(counter); counter += 1; variables.append(variable)
                imports.append(f"import {variable} from '../data/international/six/{filename}';")
        assert size == original['bytes'] and digest.hexdigest() == original['sha256']
        assert sha1.hexdigest() == original['sha1'] and f'{crc:08x}' == original['crc32']
        index_variable = 'index' + material
        index_import = f"import {index_variable} from '../data/international/six/{name}.idx';"
        imports.append(index_import); index_imports.append(index_import)
        entries.append(f"  Object.freeze({{name:{json.dumps(name)},byteLength:{size},chunks:Object.freeze([{','.join(variables)}]),indexText:{index_variable}}}),")
        index_entries.append(f"  Object.freeze({{name:{json.dumps(name)},byteLength:{size},indexText:{index_variable}}}),")
        descriptors.append({'name':name,'originalFile':source_name,'bytes':size,'sha256':digest.hexdigest(),'installerSha1':sha1.hexdigest(),'originalDriverCrc32':f'{crc:08x}',
            'index':{'file':name+'.idx','bytes':len(index),'sha256':original_index['sha256']},'chunks':chunks})
    manifest = {'schemaVersion':1,'pieces':6,'canonicalClasses':37,'completeSourceSet':True,'chunkBytes':CHUNK_BYTES,
        'dataPermissionUrl':'https://damforum.nl/bb3/viewtopic.php?t=8341','dataPermission':'Database author states these International databases are available without restrictions.',
        'scope':'Complete original six-piece theoretical WLD source files, split without changing bytes. Current-side captures require exact resolution; game draw history is separate.',
        'files':descriptors}
    (args.out/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    if args.sources_dir:
        args.sources_dir.mkdir(parents=True,exist_ok=True)
        (args.sources_dir/'international-six-data.ts').write_text('// Generated by scripts/chunk-international.py; original licensed bytes.\n'+'\n'.join(imports)+'\nexport const internationalSixFiles=Object.freeze([\n'+'\n'.join(entries)+'\n]);\n')
        (args.sources_dir/'international-six-indexes.ts').write_text('// Generated by scripts/chunk-international.py; metadata only, no data copies.\n'+'\n'.join(index_imports)+'\nexport const internationalSixIndexes=Object.freeze([\n'+'\n'.join(index_entries)+'\n]);\n')
    print(json.dumps({'status':'PASS','files':37,'chunks':counter,'sourceBytes':sum(row['bytes'] for row in descriptors),'manifestSha256':hashlib.sha256((args.out/'manifest.json').read_bytes()).hexdigest()}))

if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source',required=True,type=Path)
    parser.add_argument('--source-manifest',required=True,type=Path)
    parser.add_argument('--out',required=True,type=Path)
    parser.add_argument('--sources-dir',type=Path)
    write(parser.parse_args())
