// Latin-American Spanish for every visible string, keyed by the English.
// Server-made result text (awards, headline) is listed at the end; see ASSUMED-SDK.md.
export const strings: Record<string, string> = {
  // phone: hunt
  'Letter grid. Drag or tap touching letters to spell a word.': 'Cuadrícula de letras. Arrastra o toca letras vecinas para formar una palabra.',
  'Drag through touching letters, then lift.': 'Arrastra por letras vecinas y suelta.',
  'Submit word ✓': 'Enviar palabra ✓',
  Clear: 'Borrar',
  'I’m done ✓': 'Ya terminé ✓',
  '↩ Keep hunting': '↩ Seguir buscando',
  '✓ You’re done': '✓ Ya terminaste',
  'Waiting for {n} others, or the clock.': 'Esperando a {n} más, o al reloj.',
  'Waiting for the clock.': 'Esperando al reloj.',
  Paused: 'En pausa',
  '1 word': '1 palabra',
  '{n} words': '{n} palabras',
  '{n}+ letters': '{n}+ letras',
  '{n} letters · +{pts}': '{n} letras · +{pts}',
  '{n} letters': '{n} letras',
  'Your words': 'Tus palabras',
  '✓ {word} +{pts}': '✓ {word} +{pts}',
  '❓ {word} isn’t in our dictionary. The VIP can count it at the reveal.': '❓ {word} no está en nuestro diccionario. El VIP puede aceptarla en la revelación.',
  '🚫 {word} isn’t allowed in family mode.': '🚫 {word} no se permite en modo familiar.',
  'Your list is full for this round.': 'Tu lista está llena en esta ronda.',
  'Words need {n}+ letters.': 'Las palabras necesitan {n}+ letras.',
  // One short clause: at large text the verdict still fits the two lines the hunt keeps for it.
  '❓ {word}: the VIP decides': '❓ {word}: el VIP decide',
  '✓ Submit': '✓ Enviar',
  '⏳ Get ready…': '⏳ Prepárate…',
  // phone: VIP at the reveal, end of game
  'Up now: the best word nobody found': 'Ahora: la mejor palabra que nadie encontró',
  'Up now: no words from {names}': 'Ahora: sin palabras de {names}',
  'Up now: your words': 'Ahora: tus palabras',
  'Up now: {name}’s words': 'Ahora: palabras de {name}',
  'Everyone is watching the TV. Words that aren’t in the dictionary show up here for you to rule on.': 'Todos miran la tele. Las palabras que no están en el diccionario aparecen aquí para que decidas.',
  'You finished {place} with {total}': 'Terminaste en {place} lugar con {total}',
  'The final scores are on the TV.': 'Los puntajes finales están en la tele.',
  'Final results': 'Resultados finales',
  // card: what is left off
  '+1 more word': '+1 palabra más',
  '+{n} more words': '+{n} palabras más',
  '✕ 1 shared, so no points': '✕ 1 repetida, sin puntos',
  '✕ {n} shared, so no points': '✕ {n} repetidas, sin puntos',
  'You already have {word}.': 'Ya tienes {word}.',
  // phone: shake, reveal, tally, stage
  'Watch the TV': 'Mira la tele',
  'Your words are up right now.': 'Tus palabras están en pantalla ahora.',
  'Words are being read out. Shared ones get crossed off.': 'Se están leyendo las palabras. Las repetidas se tachan.',
  'Not in the dictionary': 'No están en el diccionario',
  'Rule on these before the tally. Everyone else is watching the TV.': 'Decide sobre estas antes del conteo. Los demás están mirando la tele.',
  'No dictionary misses so far. Everyone is watching the TV.': 'Por ahora no hay palabras fuera del diccionario. Todos miran la tele.',
  '✓ That counts': '✓ Sí cuenta',
  '✓ Counted': '✓ Aceptada',
  Undo: 'Deshacer',
  'Next card ▶': 'Siguiente ▶',
  'To the tally ▶': 'Al conteo ▶',
  'Round {n}': 'Ronda {n}',
  'Round {n}: +{pts}': 'Ronda {n}: +{pts}',
  'Round {n} of {total}': 'Ronda {n} de {total}',
  'Round {n} shakes next': 'Sigue la ronda {n}',
  'Final results next': 'Siguen los resultados finales',
  'Scores are climbing on the TV.': 'Los puntajes están subiendo en la tele.',
  'You’re {place} with {total}.': 'Vas en {place} lugar con {total}.',
  '1st': '1er',
  '2nd': '2º',
  '3rd': '3er',
  '{n}th': '{n}º',
  'Unique words': 'Palabras únicas',
  'Shared words': 'Palabras repetidas',
  Best: 'Mejor',
  'Tip: long words are rarely shared. Try endings like -ED, -ER and -ING.': 'Consejo: las palabras largas casi nunca se repiten. Prueba terminaciones como -ADO, -ERA y -ANDO.',
  'Cubes are landing…': 'Los cubos están cayendo…',
  'This round’s grid': 'La cuadrícula de esta ronda',
  'Your words · +{pts}': 'Tus palabras · +{pts}',
  '{name}’s words · +{pts}': 'Palabras de {name} · +{pts}',
  'No words': 'Sin palabras',
  'No words this round.': 'No hubo palabras esta ronda.',
  'Final scores on the TV': 'Puntajes finales en la tele',
  you: 'tú',
  // shared card
  'Words that score': 'Palabras que puntúan',
  'Shared, so no points': 'Repetidas, sin puntos',
  'not in the dictionary': 'no está en el diccionario',
  'VIP ✓ +{pts}': 'VIP ✓ +{pts}',
  '+{n} more': '+{n} más',
  '+{n} more shared': '+{n} repetidas más',
  '{word}, also found by {names}': '{word}, repetida con {names}',
  'The cubes are landing. Your grid appears here when the clock starts.': 'Los cubos están cayendo. Tu cuadrícula aparece aquí cuando arranque el reloj.',
  // TV
  'This round’s letter grid': 'La cuadrícula de letras de esta ronda',
  'Shake it up!': '¡A sacudir!',
  '{cubes} cubes · {min}+ letters · words only you find score': '{cubes} cubos · {min}+ letras · solo cuentan las que nadie más encontró',
  'Words found': 'Palabras encontradas',
  left: 'quedan',
  paused: 'en pausa',
  done: 'terminó',
  away: 'ausente',
  hunting: 'buscando',
  '{name} just found a {n}-letter word': '{name} encontró una palabra de {n} letras',
  '{name}’s words': 'Palabras de {name}',
  'The best word nobody found': 'La mejor palabra que nadie encontró',
  'No words this round': 'No hubo palabras esta ronda',
  'No words from {names}': 'Sin palabras de {names}',
  'Reveal order': 'Orden de revelación',
  'Longest unique word': 'La palabra única más larga',
  'No unique words this round': 'No hubo palabras únicas esta ronda',
  'tied with {names}': 'empata con {names}',
  'Scores after round {n}': 'Puntos tras la ronda {n}',
  // results (server text; see ASSUMED-SDK.md, "Results text")
  Wordsmith: 'Artesano de palabras',
  'Longest unique word of the game.': 'La palabra única más larga del juego.',
  'Lone Wolf': 'Lobo solitario',
  'Most words nobody else found.': 'Más palabras que nadie más encontró.',
  'Great Minds': 'Mentes brillantes',
  'Most words someone else found too.': 'Más palabras que alguien más también encontró.',
  'Quick Draw': 'Rápido como rayo',
  'Fastest first word, averaged over the rounds.': 'La primera palabra más rápida, en promedio por ronda.',
  'Dictionary Diver': 'Buzo del diccionario',
  'Most words the VIP let through.': 'Más palabras que el VIP dejó pasar.',
  'Big Round': 'Gran ronda',
  'Best single round.': 'La mejor ronda.',
  'Steady Hand': 'Pulso firme',
  'Most words traced in all.': 'Más palabras trazadas en total.',
  'Zen Garden': 'Jardín zen',
  'Fewest words traced. Very calm.': 'Menos palabras trazadas. Mucha calma.',
  'A tie at the top!': '¡Empate en la cima!',
  'Nobody scored. The cubes win.': 'Nadie anotó. Ganan los cubos.',
  '{name} out-spelled the room': '{name} deletreó mejor que todos',
  'Best word nobody found: {word}': 'La mejor palabra que nadie encontró: {word}',
  '{n} unique words': '{n} palabras únicas',
  '1 unique word': '1 palabra única',
};
