import {build} from 'esbuild';
import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {dirname,join} from 'node:path';
import {createHash} from 'node:crypto';
const root=dirname(fileURLToPath(import.meta.url));
const compatibility=createHash('sha256');
for(const path of ['src/index.ts','src/model.ts','src/scoring.ts','src/match.ts','content/categories.ts','client-save.ts','../../contract/rng.ts'])compatibility.update(path).update(await readFile(join(root,path)));
const result=await build({entryPoints:[join(root,'client.ts')],bundle:true,write:false,format:'iife',platform:'browser',target:'es2022',minify:true,legalComments:'none',charset:'ascii',sourcemap:false,define:{__G09_SAVE_COMPAT__:JSON.stringify(compatibility.digest('hex'))}});
const script=result.outputFiles[0]!.text.replace(/<\/script/gi,'<\\/script');
const template=await readFile(join(root,'src/play.template.html'),'utf8');
if(template.split('/*__BUNDLE__*/').length!==2)throw new Error('Expected exactly one bundle marker');
const zodLicense=await readFile(join(root,'node_modules/zod/LICENSE'),'utf8');
const originalLicense=await readFile(join(root,'LICENSE'),'utf8');
const notices=`Original Category Rush code, data and CSS/SVG\n${originalLicense}\nBundled dependency: Zod 4.1.12\n${zodLicense}`.replace(/--/g,'- -');
const notice=`<!-- ${notices}\n-->\n`;
const html=template.replace('/*__BUNDLE__*/',()=>script).replace('<html lang="en">',()=>notice+'<html lang="en">');
if(/<(?:script|link)[^>]+(?:src|href)\s*=/i.test(html))throw new Error('External asset in offline HTML');
await writeFile(join(root,'play.html'),html);
console.log(`Built self-contained play.html (${Buffer.byteLength(html)} bytes).`);
