import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {chromium} from 'playwright';
const root=resolve(import.meta.dirname,'..'),mode=process.argv[2]??'baseline';
assert(['baseline','after'].includes(mode));
const output=resolve(root,`evidence/browser/round-3-resume-${mode}`);await mkdir(output,{recursive:true});
const digest=x=>createHash('sha256').update(x).digest('hex'),key='category-rush.saved-game.v1';
const report={mode,sourceSha256:digest(await readFile(resolve(root,'play.html'))),runnerSha256:digest(await readFile(new URL(import.meta.url))),startedAt:new Date().toISOString(),checks:[],cases:[],details:[],runtime:{errors:[],requests:[],dialogs:[]},passed:false};
console.log(JSON.stringify({pid:process.pid,mode,sourceSha256:report.sourceSha256}));
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});report.browser=browser.version();let context,page;
async function fresh({raw,storage}={}){if(context)await context.close();context=await browser.newContext({viewport:{width:1920,height:1080},offline:true});if(raw!==undefined||storage)await context.addInitScript(({raw,storage,key})=>{if(raw!==undefined)localStorage.setItem(key,raw);if(storage==='denied')for(const method of ['getItem','setItem','removeItem'])Storage.prototype[method]=()=>{throw new DOMException('Blocked for test','SecurityError');};if(storage==='quota')Storage.prototype.setItem=()=>{throw new DOMException('Quota for test','QuotaExceededError');};},{raw,storage,key});page=await context.newPage();page.on('pageerror',e=>report.runtime.errors.push(String(e)));page.on('request',r=>{if(!r.url().startsWith('file:'))report.runtime.requests.push(r.url());});page.on('dialog',d=>{report.runtime.dialogs.push(d.message());void d.dismiss();});await page.clock.install();await page.goto(pathToFileURL(resolve(root,'play.html')).href);}
async function begin(count,rounds=1,kinds=[]){await page.locator('#rounds').selectOption(String(rounds));await page.locator('#seconds').selectOption('60');for(let i=2;i<count;i++)await page.locator('#add-player').click();await page.getByLabel('Player 1 name',{exact:true}).fill('Reload Probe');for(const [seat,kind] of kinds)await page.getByLabel(`Player ${seat} type`,{exact:true}).selectOption(kind);await page.getByRole('button',{name:'Let’s play'}).click();}
const ready=async()=>page.locator('#ready').click(),lock=async()=>page.getByRole('button',{name:'Lock my',exact:false}).click();
const saved=async()=>JSON.parse(await page.evaluate(key=>localStorage.getItem(key),key));
async function values(phase){return {phase,score:await page.locator('.points').allTextContents(),draft:phase==='answer'?await page.locator('#answer-0').inputValue():null,keepSelected:phase==='review'?await page.locator('.vote-button[data-value=true]').first().getAttribute('aria-pressed'):null,timer:phase==='scores'?null:await page.locator('#timer').innerText(),receiptCount:await page.locator('.receipt-category').count()};}
async function check(name,fn){const row={name,passed:false};report.checks.push(row);try{await fn();row.passed=true;console.log(JSON.stringify(row));}catch(e){row.error=String(e);throw e;}}
async function scoreRound(count,answerCount=1){for(let i=0;i<count;i++){await ready();if(i===0){const letter=await page.locator('.letter-badge').innerText();for(let c=0;c<answerCount;c++)await page.locator(`#answer-${c}`).fill(`${letter} answer-${c}`);}await lock();}let ballots=0;while(await page.locator('#ready').count()){assert(++ballots<=96);assert.match(await page.locator('.handover .eyebrow').innerText(),/private ballot/i);await ready();await lock();}return ballots;}
try{
 for(const count of [2,8])for(const phase of ['answer','review','scores']){
  await fresh();await begin(count);
  await check(`${count} humans reload during ${phase}`,async()=>{
   await ready();const letter=await page.locator('.letter-badge').innerText(),probe=letter+' reload-probe';await page.locator('#answer-0').fill(probe);
   if(phase==='answer')await page.clock.fastForward(10000);
   else{await lock();for(let i=1;i<count;i++){await ready();await lock();}await ready();if(phase==='review'){await page.locator('.vote-button[data-value=true]').click();await page.clock.fastForward(2000);}else{await lock();for(let i=1;i<count;i++){await ready();await lock();}}}
   const before=await values(phase);const caseRow={count,phase,before,resumeAvailable:false,restored:false};report.cases.push(caseRow);if(mode==='after')caseRow.savedBeforeReload=await saved();await page.reload();if(mode==='after')caseRow.savedAfterReload=await saved();await page.clock.fastForward(120000);
   if(mode==='baseline'){assert.equal(await page.locator('#setup-form').count(),1);assert.equal(await page.locator('#resume-game').count(),0);assert.equal(await page.getByLabel('Player 1 name',{exact:true}).inputValue(),'Alex');assert.equal(await page.locator('.points').count(),0);caseRow.resumeAvailable=false;}
   else{assert.equal(await page.locator('#resume-game').count(),1);const hiddenBeforeResume=await page.locator('.answer-input,.vote-card,.score-row').count()===0;assert(hiddenBeforeResume);await page.locator('#resume-game').click();caseRow.savedAfterResume=await saved();let privateHandover=false;if(phase!=='scores'){privateHandover=await page.locator('.handover').count()===1&&await page.locator('.answer-input,.vote-card').count()===0;assert(privateHandover);assert(!await page.locator('#main').innerText().then(t=>t.includes(probe)));await ready();}const after=await values(phase);Object.assign(caseRow,{after,hiddenBeforeResume,privateHandover,resumeAvailable:true,savedAfterReady:await saved()});assert.deepEqual(after,before,'exact draft, ballot, score, receipts and active time restored');if(phase==='scores')assert.equal(after.receiptCount,12);caseRow.restored=true;}
  });
 }
 if(mode==='after'){
  await check('reloading twice on a restored handover keeps draft private and timer frozen',async()=>{await fresh();await begin(2);await ready();await page.locator('#answer-0').fill('Private repeated draft');await page.clock.fastForward(10000);const timer=await page.locator('#timer').innerText();await page.reload();await page.locator('#resume-game').click();await page.reload();await page.clock.fastForward(120000);await page.locator('#resume-game').click();assert.equal(await page.locator('.handover').count(),1);assert.equal(await page.locator('#modal-root [role=dialog]').count(),0);assert(!await page.locator('#main').innerText().then(t=>t.includes('Private repeated draft')));await ready();assert.equal(await page.locator('#answer-0').inputValue(),'Private repeated draft');assert.equal(await page.locator('#timer').innerText(),timer);report.details.push({case:'double handover reload',timer,draft:await page.locator('#answer-0').inputValue()});});
  await check('saved host pause restores controls and waits before private Ready',async()=>{await fresh();await begin(2);await ready();await page.locator('#answer-0').fill('Paused draft');await page.clock.fastForward(10000);const timer=await page.locator('#timer').innerText();await page.locator('#vip-button').click();await page.reload();await page.clock.fastForward(120000);await page.locator('#resume-game').click();assert.equal(await page.locator('#modal-title').innerText(),'Host controls');assert.equal(await page.locator('.answer-input').count(),0);await page.clock.fastForward(120000);await page.locator('#modal-root [data-close]').click();await ready();assert.equal(await page.locator('#timer').innerText(),timer);assert.equal(await page.locator('#answer-0').inputValue(),'Paused draft');report.details.push({case:'host pause',timer,pausedSave:(await saved()).state.phase.paused??null});});
  await check('near-expiry restore times out through the real submit flow',async()=>{await fresh();await begin(2);await ready();await page.locator('#answer-0').fill('Near expiry draft');await page.clock.fastForward(59000);assert.equal(await page.locator('#timer').innerText(),'0:01');await page.reload();await page.locator('#resume-game').click();await ready();assert.equal(await page.locator('#timer').innerText(),'0:01');await page.clock.fastForward(1200);assert.equal(await page.locator('.handover').count(),1);assert((await page.locator('.handover h2').innerText()).includes('Sam'));const snapshot=await saved();assert.equal(snapshot.state.submitted.p1,true);assert.equal(snapshot.state.answers.p1[0],'Near expiry draft');report.details.push({case:'near expiry',submitted:snapshot.state.submitted.p1,answer:snapshot.state.answers.p1[0],next:snapshot.activeHuman});});
  await check('host skip and end remain available after resume with settled scores',async()=>{await fresh();await begin(2);await ready();await page.locator('#answer-0').fill('Unfinished draft');await page.reload();await page.locator('#resume-game').click();await page.locator('#vip-button').click();await page.locator('#host-skip').click();assert.equal(await page.locator('.score-row').count(),2);assert.deepEqual(await page.locator('.points').allTextContents(),['0','0']);await page.locator('#vip-button').click();await page.locator('#host-end').click();await page.locator('#confirm-end').click();assert.match(await page.locator('#next-round').innerText(),/^Play again\s+→$/);await page.locator('#next-round').click();assert.equal(await page.locator('#setup-form').count(),1);assert.equal(await page.evaluate(key=>localStorage.getItem(key),key),null);await page.reload();assert.equal(await page.locator('#resume-game').count(),0);});
  await check('discard removes the saved game without starting or exposing its draft',async()=>{await fresh();await begin(2);await ready();await page.locator('#answer-0').fill('Discard private');await page.reload();await page.locator('#discard-save').click();assert.equal(await page.locator('#resume-game').count(),0);assert.equal(await page.locator('.answer-input').count(),0);assert.equal(await page.evaluate(key=>localStorage.getItem(key),key),null);assert.equal(await page.getByRole('button',{name:'Let’s play'}).isEnabled(),true);});
  await check('storage denial and quota failure never claim the game was saved',async()=>{for(const storage of ['denied','quota']){await fresh({storage});await begin(2);await ready();await page.locator('#answer-0').fill('Storage unavailable');await page.clock.fastForward(1000);assert((await page.locator('#save-status').innerText()).includes('could not be saved'));assert.equal(await page.locator('#answer-0').inputValue(),'Storage unavailable');await lock();assert.equal(await page.locator('.handover').count(),1);report.details.push({case:'storage failure',storage,status:await page.locator('#save-status').innerText()});}});
  await check('corrupt and stale local saves offer discard and a clean new game',async()=>{await fresh();await begin(2);const raw=await page.evaluate(key=>localStorage.getItem(key),key);const stale=JSON.parse(raw);stale.compat='f'.repeat(64);for(const [kind,invalid] of [['corrupt','{'],['stale',JSON.stringify(stale)]]){await fresh({raw:invalid});assert.equal(await page.locator('#resume-game').count(),0);assert.equal(await page.locator('#discard-save').count(),1);assert((await page.locator('.resume-panel').innerText()).includes(kind==='corrupt'?'could not be read':'different version'));await page.locator('#discard-save').click();assert.equal(await page.evaluate(key=>localStorage.getItem(key),key),null);await begin(2);assert.equal(await page.locator('#ready').count(),1);report.details.push({case:'invalid save',kind});}});
  await check('mixed-roster resume preserves exact future bot output and RNG counters',async()=>{await fresh();await begin(4,2,[[2,'easy'],[3,'normal'],[4,'sharp']]);const oldRaw=await page.evaluate(key=>localStorage.getItem(key),key);const before=JSON.parse(oldRaw);assert(before.state.submitted.p2&&before.state.submitted.p3&&before.state.submitted.p4);await ready();await lock();while(await page.locator('#ready').count()){await ready();await lock();}await page.locator('#next-round').click();const uninterrupted=await saved();await fresh({raw:oldRaw});await page.locator('#resume-game').click();await ready();await lock();while(await page.locator('#ready').count()){await ready();await lock();}await page.locator('#next-round').click();const restored=await saved();assert.equal(restored.state.round,2);assert.deepEqual(restored.state.answers,uninterrupted.state.answers);assert.deepEqual(restored.botRngs,uninterrupted.botRngs);assert.deepEqual(restored.state.rng,uninterrupted.state.rng);assert.deepEqual(restored.state.scores,uninterrupted.state.scores);report.details.push({case:'mixed bot continuation',seed:before.config.seed,beforeRng:before.botRngs,afterRng:restored.botRngs,answers:restored.state.answers,scores:restored.state.scores});});
  await check('selected historical gains describe that round while totals remain current',async()=>{await fresh();await begin(2,2);await scoreRound(2,1);await page.locator('#next-round').click();await scoreRound(2,2);const currentTotals=await page.locator('.points').allTextContents();assert.deepEqual(currentTotals,['3','0']);await page.locator('#history-round').selectOption('1');const gains=await page.locator('.score-gain').allTextContents();assert.deepEqual(gains,['+1 in round 1','+0 in round 1']);assert.deepEqual(await page.locator('.points').allTextContents(),currentTotals);await page.reload();await page.locator('#resume-game').click();assert.equal(await page.locator('#history-round').inputValue(),'1');assert.deepEqual(await page.locator('.score-gain').allTextContents(),gains);report.details.push({case:'historical gains',selectedRound:1,gains,currentTotals});});
  await check('Ready focuses Lock my ballot when every answer has the wrong initial',async()=>{await fresh();await begin(2);await ready();const letter=await page.locator('.letter-badge').innerText();await page.locator('#answer-0').fill((letter==='Z'?'Y':'Z')+' wrong');await lock();await ready();await lock();await ready();assert.equal(await page.locator('.vote-button:enabled').count(),0);assert.equal(await page.evaluate(()=>document.activeElement?.textContent?.trim()),'Lock my ballot →');report.details.push({case:'invalid review focus',enabledVotes:0,focusedText:await page.evaluate(()=>document.activeElement?.textContent?.trim())});});
 }
 await check('exact HTML and offline runtime stayed clean',async()=>{assert.deepEqual(report.runtime,{errors:[],requests:[],dialogs:[]});assert.equal(digest(await readFile(resolve(root,'play.html'))),report.sourceSha256);});
 report.passed=report.checks.every(c=>c.passed);
}catch(e){report.failure=String(e);process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();if(context)await context.close();await browser.close();await writeFile(resolve(output,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,sourceSha256:report.sourceSha256,failure:report.failure,closedAt:report.finishedAt}));}
