import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {resolve} from 'node:path';
import {chromium} from 'playwright';
import {stageGuards,sourceCommit} from '../../scripts/check-stages.mjs';
import {gameInputHashes} from '../../scripts/game-inputs.mjs';
const directory=resolve('.work/american-ready-private'),startedAt=new Date().toISOString();
assert.equal(process.version,'v22.16.0');assert.equal(sourceCommit(),'e7a5c6463af2f0033ff08d333fb378ad160c1e43');
const hash=async path=>{const h=createHash('sha256');for await(const bytes of createReadStream(path))h.update(bytes);return h.digest('hex');};
const old=JSON.parse(await readFile('.work/hosted-fa-final/extracted/.work/checks/stage-node.json','utf8'));
assert.equal(old.sourceCommit,'fa0b337e1178177ff5b871acae697897c687ee11');
const inputs=await gameInputHashes(),gold=JSON.parse(await readFile('.work/hosted-fa-final/extracted/.work/checks/league.json','utf8'));
assert.deepEqual(inputs,gold.gameInputHashes);assert.equal(Object.keys(inputs).length,127);
const guards=await stageGuards(),allowed=new Set(['../../.github/workflows/G10.yml','README.md','VERIFY.md','NEXT.md','LOOP.md','ASSUMPTIONS.md','SHA256SUMS.txt']);
assert.deepEqual(Object.keys(guards).sort(),Object.keys(old.sourceGuardsAfter).sort());
const divergences=[];
for(const [path,digest] of Object.entries(guards))if(digest!==old.sourceGuardsAfter[path]){assert(allowed.has(path),path);divergences.push({path,currentSha256:digest,acceptedFaSha256:old.sourceGuardsAfter[path],scope:'Documentation or verification-host mirror only; no accepted gameplay change.'});}
const fileHashes={};for(const [path,digest] of Object.entries(guards))fileHashes[resolve(path)]=digest;
const documentationBridge=[];
for(const path of ['README.md','VERIFY.md','NEXT.md','LOOP.md','ASSUMPTIONS.md','SHA256SUMS.txt']){
 const gitPath='jobs/G10-checkers/'+path,currentCommit=sourceCommit();
 const currentBytes=await readFile(path),currentGitBytes=execFileSync('git',['show',currentCommit+':'+gitPath],{maxBuffer:4*1024*1024}),acceptedBytes=execFileSync('git',['show',old.sourceCommit+':'+gitPath],{maxBuffer:4*1024*1024});
 assert.deepEqual(currentBytes,currentGitBytes,'Current documentation must equal immutable current commit: '+path);
 const currentSha256=createHash('sha256').update(currentBytes).digest('hex'),acceptedFaSha256=createHash('sha256').update(acceptedBytes).digest('hex');
 fileHashes[resolve(path)]=currentSha256;
 documentationBridge.push({path,currentCommit,currentGitBlob:execFileSync('git',['rev-parse',currentCommit+':'+gitPath],{encoding:'utf8'}).trim(),acceptedFaCommit:old.sourceCommit,acceptedFaGitBlob:execFileSync('git',['rev-parse',old.sourceCommit+':'+gitPath],{encoding:'utf8'}).trim(),currentSha256,acceptedFaSha256,byteIdentical:currentSha256===acceptedFaSha256,scope:'Six current documentation/checksum files are explicitly immutable-Git compared and frozen separately from the existing349 gameplay/runtime guards; any divergence is documentation/evidence history, not transferred hosted acceptance.'});
}
assert.equal(documentationBridge.length,6);
for(const name of ['candidate-browser.ts','candidate-source.json','candidate-bootstrap.js','original-bootstrap.js','american-ready-marker.html','bootstrap-controls.json','strict-overlay.json','delta-controls.json','http-byte-controls.json','stream-server.mjs','observe-player.mjs','prepare-ready.mjs','dist/worker-american.mjs','dist/worker-international.mjs'])fileHashes[directory+'/'+name]=await hash(directory+'/'+name);
fileHashes[process.execPath]=await hash(process.execPath);assert.equal(fileHashes[process.execPath],'8142d37c6f2f372ef040419e7a111a6baf17df89f8078d02447d6c639ae20c1d');
const executable=chromium.executablePath();fileHashes[executable]=await hash(executable);
const delta=JSON.parse(await readFile(directory+'/delta-controls.json','utf8')),http=JSON.parse(await readFile(directory+'/http-byte-controls.json','utf8'));
assert.equal(delta.status,'PASS');assert.equal(http.status,'PASS');assert.equal(http.deltaManifestSha256,fileHashes[directory+'/delta-controls.json']);assert.equal(http.serverSha256,fileHashes[directory+'/stream-server.mjs']);
assert.equal(await hash(delta.basePath),delta.baseSha256);
assert.deepEqual(await stageGuards(),guards);
const ready={status:'READY_NOT_RUN',nonce:'G10-native-player-'+randomUUID(),startedAt,closedAt:new Date().toISOString(),currentPublicHead:sourceCommit(),acceptedBaselineHead:delta.acceptedBaselineHead,baselineBytes:delta.baseBytes,baselineSha256:delta.baseSha256,candidateBytes:delta.resultBytes,candidateSha256:delta.resultSha256,runtime:process.version,runtimeBinarySha256:fileHashes[process.execPath],browserExecutable:executable,browserExecutableSha256:fileHashes[executable],stageGuardCount:Object.keys(guards).length,acceptedGameplayInputCount:Object.keys(inputs).length,acceptedFaDivergences:divergences,documentationBridge,fileHashes,wholeTrialTimeoutMs:360000,scope:'Explicit root grant required before any browser/native elapsed launch. Matched complete-byte HTTP diagnostic: native bot-configured Start enable/trusted click/first legal American Strong move on desktop and phone4x, full-load International safety and matched exact worker/search/cursor/core behavior. Separate from final offline/frame/current-source CI acceptance; one pair/profile, reversed phone order, no cold-cache/distribution claim. All source-only and client complete byte proofs naturally CLOSED.'};
await writeFile(directory+'/native-ready.json',JSON.stringify(ready,null,2)+'\n');console.log(JSON.stringify({...ready,fileHashes:undefined,browserExecutable:undefined}));
